---
- name: converge
  hosts: all
  vars:
    # Install all HashiCorp software
    hashicorp_install_boundary: true
    hashicorp_install_consul: true
    hashicorp_install_nomad: true
    hashicorp_install_packer: true
    hashicorp_install_serf: true
    hashicorp_install_terraform: true
    hashicorp_install_vagrant: true
    hashicorp_install_vault: true
    hashicorp_install_waypoint: true

    hashicorp_use_official_packages: true

    # Purge all ZIP based releases
    hashicorp_purge_zip_releases: true
  tasks:

    - name: Include mesaguy.hashicorp role
      ansible.builtin.include_role:
        name: ansible-hashicorp
