---
- name: Verify that "gpg" command is in PATH
  command: gpg --version
  changed_when: false

- name: Check if HashiCorp is present in GPG key store
  become: true
  command: gpg --list-keys --keyid-format=long
  changed_when: false
  register: gpg_output

- name: Import HashiCorp's 2014 GPG public key
  become: true
  shell:
    cmd: |
       cat << EOF | gpg --import
       {{ lookup("file", "files/hashicorp-20140226.asc") }}
       EOF
  when: not '91A6E7F85D05C65630BEF18951852D87348FFC4C' in gpg_output.stdout

- name: Import HashiCorp's 2021 GPG public key
  become: true
  shell:
    cmd: |
       cat << EOF | gpg --import
       {{ lookup("file", "files/hashicorp-20210419.asc") }}
       EOF
  when: not 'C874011F0AB405110D02105534365D9472D7468F' in gpg_output.stdout

- name: Import HashiCorp's 2023 GPG public key
  become: true
  shell:
    cmd: |
       cat << EOF | gpg --import
       {{ lookup("file", "files/hashicorp-20230110.asc") }}
       EOF
  when: not '798AEC654E5C15428C8E42EEAA16FCBCA621E701' in gpg_output.stdout
