---
- name: No official package available
  fail:
    msg: '{{ hashicorp_software_name }} is not available as an official package and must be installed as ZIP'
  when:
    - hashicorp_software_name not in hashicorp_official_package_names

- block:
    - name: Install apt-transport-https
      become: true
      package:
        name: apt-transport-https

    - name: Add HashiCorp Apt repo GPG public key
      become: true
      ansible.builtin.apt_key:
        data: "{{ lookup('file', '{{ role_path }}/files/hashicorp-apt.asc') }}"
        state: present

    - name: Setup HashiCorp Apt repository
      become: true
      ansible.builtin.apt_repository:
        repo: 'deb [arch={{ hashicorp_arch }}] {{ hashicorp_apt_mirror }} {{ ansible_distribution_release }} main'
        state: present
        filename: hashicorp
      register: hashicorp_apt_repo_setup
  when:
    - ansible_os_family == 'Debian'
    - hashicorp_apt_repo_setup is undefined

- block:
    - name: Add HashiCorp Test yum repository
      become: true
      yum_repository:
        name: hashicorp-test
        description: Hashicorp Test - $basearch
        baseurl: '{{ hashicorp_yum_mirror }}/{{ hashicorp_yum_release }}/$releasever/$basearch/test'
        enabled: '{{ hashicorp_enable_yum_test_repo | default(0) }}'
        gpgcheck: 1
        gpgkey: https://rpm.releases.hashicorp.com/gpg

    - name: Add HashiCorp Stable yum repository
      become: true
      yum_repository:
        name: hashicorp
        description: Hashicorp Stable - $basearch
        baseurl: '{{ hashicorp_yum_mirror }}/{{ hashicorp_yum_release }}/$releasever/$basearch/stable'
        enabled: 1
        gpgcheck: 1
        gpgkey: https://rpm.releases.hashicorp.com/gpg
      register: hashicorp_yum_repo_setup
  when:
    - ansible_os_family == 'RedHat'
    - hashicorp_yum_repo_setup is undefined

- name: Install {{ hashicorp_software_name }}
  become: true
  ansible.builtin.package:
    name: '{{ hashicorp_software_name }}'
    state: '{{ hashicorp_software_state }}'
