---
- name: No official package available
  ansible.builtin.fail:
    msg: '{{ hashicorp_software_name }} is not available as an official package and must be installed as ZIP'
  when:
    - hashicorp_software_name not in hashicorp_official_package_names

- block:
    - name: Install apt-transport-https
      become: true
      ansible.builtin.package:
        name: apt-transport-https

    - name: Add HashiCorp Apt repo GPG public key
      become: true
      ansible.builtin.apt_key:
        data: "{{ lookup('file', '{{ role_path }}/files/hashicorp-apt.asc') }}"
        state: present

    - name: Add HashiCorp Apt repo 2023 GPG public key
      become: true
      ansible.builtin.apt_key:
        data: "{{ lookup('file', '{{ role_path }}/files/hashicorp-20230110.asc') }}"
        state: present

    - name: Setup HashiCorp Apt repository
      become: true
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/hashicorp.list
        owner: root
        group: root
        mode: 0644
        content: |
          ###############################################################################
          # HashiCorp official
          ###############################################################################
          deb [arch={{ hashicorp_arch }}] {{ hashicorp_apt_mirror }} {{ hashicorp_apt_repo_release | default(ansible_distribution_release) }} main

    - name: Update Apt package data
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Define apt repo as setup
      ansible.builtin.set_fact:
        hashicorp_apt_repo_setup: true
  when:
    - ansible_os_family == 'Debian'
    - hashicorp_apt_repo_setup is undefined

- block:
    - name: Add HashiCorp Test yum repository
      become: true
      yum_repository:
        name: hashicorp-test
        description: Hashicorp Test - $basearch
        baseurl: '{{ hashicorp_yum_mirror }}/{{ hashicorp_yum_release }}/$releasever/$basearch/test'
        enabled: '{{ hashicorp_enable_yum_test_repo | default(0) }}'
        gpgcheck: 1
        gpgkey: https://rpm.releases.hashicorp.com/gpg

    - name: Add HashiCorp Stable yum repository
      become: true
      yum_repository:
        name: hashicorp
        description: Hashicorp Stable - $basearch
        baseurl: '{{ hashicorp_yum_mirror }}/{{ hashicorp_yum_release }}/$releasever/$basearch/stable'
        enabled: 1
        gpgcheck: 1
        gpgkey: https://rpm.releases.hashicorp.com/gpg
      register: hashicorp_yum_repo_setup
  when:
    - ansible_os_family == 'RedHat'
    - hashicorp_yum_repo_setup is undefined

- name: Install {{ hashicorp_software_name }}
  become: true
  ansible.builtin.package:
    name: "{{ hashicorp_software_name }}{% if hashicorp_software_specific_version %}\
      {% if ansible_os_family == 'RedHat' %}-{% else %}={% endif %}\
      {{ hashicorp_software_specific_version }}{% endif %}"
    state: '{{ hashicorp_software_state }}'
  register: hashicorp_package_install
  retries: 5
  delay: 10
  until: hashicorp_package_install is succeeded
