---
- name: No distro package available
  fail:
    msg: '{{ hashicorp_software_name }} is not available as an distro package and must be installed as ZIP'
  when:
    - hashicorp_software_name not in hashicorp_distro_package_names

- name: Install {{ hashicorp_software_name }} via distro package
  become: true
  package:
    name: '{{ hashicorp_distro_package_names[hashicorp_software_name] }}'
  register: hashicorp_package_install
  retries: 5
  delay: 10
  until: hashicorp_package_install is succeeded
