---
# tasks file for mesaguy.hashicorp

- name: Gather Operating System specific variables
  include_vars: '{{ os_var_file }}'
  loop_control:
    loop_var: os_var_file
  with_first_found:
    - 'distribution/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - 'distribution/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
    - 'distribution/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
    - 'distribution/{{ ansible_distribution }}.yml'
    - 'os/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
    - 'os/{{ ansible_os_family }}.yml'
    - 'os/catchall.yml'

- name: Gather Architecture specific variables
  include_vars: 'os-architecture/{{ ansible_system }}-{{ ansible_architecture }}.yml'

- name: Determine architecture short name
  set_fact:
    hashicorp_arch: '{{ ansible_userspace_architecture | replace("x86_64", "amd64") }}'

- name: Include variable file containing current HashiCorp variables
  include_vars:
    file: versions.yml
    name: hashicorp_versions

- name: Install specific HashiCorp software
  include_tasks: install.yml
  loop_control:
    loop_var: hashicorp_install_name
  with_items: '{{ hashicorp_install }}'
  vars:
    hashicorp_software_name: '{{ hashicorp_install_name | regex_replace("==.*", "") }}'
    hashicorp_software_specific_version: "{% if '==' in hashicorp_install_name %}\
      {{ (hashicorp_install_name | regex_replace('.*==', '')) | default('', true) }}\
      {% endif %}"
  when:
    - hashicorp_install is defined
    - hashicorp_install_name | regex_replace("==.*", "") in hashicorp_software_names

- name: Install HashiCorp software
  include_tasks: install.yml
  loop_control:
    loop_var: hashicorp_software_name
  with_items: '{{ hashicorp_software_names }}'
  when:
    - hashicorp_install is undefined
    - lookup('vars', 'hashicorp_install_' + hashicorp_software_name | replace ('-', '_'), default=false)
