---
- name: converge
  hosts: all
  vars:
    hashicorp_use_official_packages: true
  tasks:
    - name: Include mesaguy.hashicorp role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        hashicorp_install:
          - consul
          - nomad==1.0.0
          - terraform
