---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${IMAGE_DISTRO:-archlinux}-${IMAGE_TAG:-latest}
    image: mesaguy/ansible-molecule-${IMAGE_DISTRO:-archlinux}:${IMAGE_TAG:-latest}
lint: |
  set -e
  yamllint --config-file=tests/yamllint.yml meta tasks vars
  ansible-lint
verifier:
  name: testinfra
  directory: ../resources/tests/
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
