---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${IMAGE_DISTRO:-archlinux}
    image: mesaguy/ansible-molecule-${IMAGE_DISTRO:-archlinux}:${IMAGE_TAG:-latest}
verifier:
  name: testinfra
provisioner:
  name: ansible
