---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${MOLECULE_DISTRO:-archlinux}
    image: mesaguy/ansible-molecule-${MOLECULE_DISTRO:-archlinux}:${MOLECULE_TAG:-latest}
verifier:
  name: testinfra
provisioner:
  name: ansible
