---
- name: converge
  hosts: all
  vars:
    hashicorp_use_distro_packages: true

    # Purge all ZIP based releases
    hashicorp_purge_zip_releases: true
  tasks:
    - block:
        - name: Include Archlinux variables
          include_vars: ../../vars/distribution/Archlinux.yml

        - name: Setup pacman package mirror
          become: true
          copy:
            dest: /etc/pacman.d/mirrorlist
            owner: root
            group: root
            mode: 0644
            content: |
              Server = {{ lookup("env", "HASHICORP_PACMAN_MIRROR") }}
          when:
            - lookup("env", "HASHICORP_PACMAN_MIRROR") | length > 1

        - name: Update pacman cache, "pacman -Syyu"
          become: true
          ansible.builtin.command: pacman -Syyu
          register: hashicorp_update_pacman_cache
          # Don't fail idempotent test for this
          changed_when: false
          when:
            - hashicorp_update_pacman_cache is undefined

        - name: Include mesaguy.hashicorp role
          ansible.builtin.include_role:
            name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
          vars:
            hashicorp_install: '{{ hashicorp_distro_package_names.keys() | list }}'
      when: ansible_distribution == 'Archlinux'

    - block:
        - name: Include Gentoo variables
          include_vars: ../../vars/distribution/Gentoo.yml

        - name: Create portage keywords directory
          ansible.builtin.set_fact:
            hashicorp_install: '{{ hashicorp_distro_package_names.keys() | list }}'

        - name: Create portage keywords directory
          become: true
          ansible.builtin.file:
            path: /etc/portage/package.accept_keywords
            owner: root
            group: root
            mode: 0755
            state: directory

        - name: Create portage keyworks directory
          become: true
          ansible.builtin.copy:
            dest: /etc/portage/package.accept_keywords/hashicorp
            owner: root
            group: root
            mode: 0644
            content: |
              {% for name in hashicorp_distro_package_names %}
              {{ hashicorp_distro_package_names[name] }}
              {% endfor %}

        - name: Allow all licenses
          become: true
          ansible.builtin.lineinfile:
            path: /etc/portage/make.conf
            regexp: ACCEPT_LICENSE.*
            line: 'ACCEPT_LICENSE="*"'

        - name: Disable usersandbox to allow Go to build in container
          become: true
          ansible.builtin.lineinfile:
            path: /etc/portage/make.conf
            regexp: FEATURE.*
            line: FEATURES="-usersandbox"

        - name: Install Git
          # Required to build some of the HashiCorp software, but not
          # automatically installed
          become: true
          ansible.builtin.package:
            name: dev-vcs/git

        - name: Include mesaguy.hashicorp role
          ansible.builtin.include_role:
            name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      when: ansible_distribution == 'Gentoo'
