#!/bin/bash

pipenv install

echo "-> Test ansible"
if ! pipenv run ansible --version ; then
    echo "---> Ansible failed to run"
    echo "---> Reinstall SELinux libraries"
    pipenv run pip uninstall selinux -y; pipenv install
fi

for VARIABLE in $(echo "$1" | sed 's/#/ /g')
do
    export $VARIABLE
done

shift

pipenv run molecule $@
