#!/bin/bash


export MOLECULE_DOCKER_IMAGE="$(echo $1 | sed -e 's/__/:/g' -e 's/--/\//g')"
export MOLECULE_DOCKER_INSTANCE_NAME="$(basename "$1" | sed -e 's/__/_/g' -e 's/.*--//g')"
SCENARIO="$2"
if [ -n "$SCENARIO" ] ; then
    SCENARIO="-s $SCENARIO"
fi

pipenv run molecule test $SCENARIO
