#!/bin/bash

function get_latest() {
    NAME=$1
    lynx -dump -nolist https://releases.hashicorp.com/$NAME/ | grep ${NAME}_ | awk '{print $2}' | grep -vE '.*(\-alpha.*|\+ent.*|\-ent.*|\-connect.*|\-rc.*|\-beta.*)' | sort --version-sort | tail -1 | sed "s/${NAME}_//g"
}


function get_latest_docker() {
    NAME=$1
    curl -s "https://registry.hub.docker.com/v2/repositories/library/${NAME}/tags/" | jq -r '."results"[]["name"]' | grep -v '^latest$' | grep -vE '.*(\-alpha.*|\+ent.*|\-ent.*|\-connect.*|\-rc.*|\-beta.*)' | head -1
}

function check_if_update () {
    FILENAME="$1"
    echo "Checking \"$FILENAME\" for changes"
    if diff "$FILENAME" "${FILENAME}.tmp" ; then
        # File content hasn't changed, remove new file
        rm -f "${FILENAME}.tmp"
    else
        mv "${FILENAME}.tmp" "$FILENAME"
        export UPDATED=1
    fi
}

cat > vars/versions.yml.tmp << EOF
---
boundary: $(get_latest boundary)
consul: $(get_latest consul)
envconsul: $(get_latest envconsul)
nomad: $(get_latest nomad)
packer: $(get_latest packer)
sentinel: $(get_latest sentinel)
serf: $(get_latest serf)
terraform: $(get_latest terraform)
vagrant: $(get_latest vagrant)
vault: $(get_latest vault)
vault_ssh_helper: $(get_latest vault-ssh-helper False)
waypoint: $(get_latest waypoint)
EOF
check_if_update vars/versions.yml

cat > vars/docker_versions.yml.tmp << EOF
---
consul: $(get_latest_docker consul)
vault: $(get_latest_docker vault)
EOF
check_if_update vars/docker_versions.yml

if [ -z "$UPDATED" ] ; then
    # No updates, return a non-standard exit value to signify a non-error
    exit 3
fi
